### ISSUE TITLE
problems opening

### ISSUE THREAD

**Issue by Raum2001** [linsomniac/MarlinSKRMiniE3v2.0Files#2]
So I downloaded the files, but what do I need to do after it (I am pretty new to all of this)? Can you please help me with it?

**Comment by linsomniac** [comment]
You copy it to an SD card as "firmware.bin", and then put it in the printer and boot it.  When it boots, it should flash the file.  You can verify it has flashed it by looking at the sd card after it has booted and the file is renamed, maybe to "firmware.cur".  Note that this firmware is for an Ender 3 Pro with the SKR Mini E3 v2 and BLTouch installed.  It won't work with any other configuration.
